### PR TITLE
fix(component/progressbar):  fix progressbar showing label when progress == 0

### LINKED ISSUE #696: The `progress` 0 is shown above a progress bar with `labelProgress` is `false`
**Describe the bug**
With settings:
```
progress: 0,
labelText: false
labelProgress: false
```
The progress `0` is shown above a progress bar.

**To Reproduce**

1. Clone source code.
2. On branch `main`, run `yarn run start:storybook`
3. Select `Progress`, set property `progress` to `0`

**Expected behavior**
The `0` won't be shown if `labelProgress` is `false`

**Screenshots**
Flowbite_react_progress_bug

**System information:**

- Device: MacBook pro 13, M1, 2020
- Resolution: 2560 × 1600
- OS: Mac OS Ventura 13.3.1
- Browser: Brave
- Version: Version 1.50.114 Chromium: 112.0.5615.49 (Official Build) (arm64)

**Project information:**

- Tailwind: 3.0.0
- Flowbite: 1.4.7
- Flowbite React: 0.1.2
- Type: CRA

**Additional context**

### PR DESCRIPTION
**Pull request by SrivatsaRUpadhya**
## Description

Progress bar shows labels even when it is disabled at progress value is 0
The conditional rendering using the '&&' would return 0 on condition being false which would get displayed when progress value is 0. This was fixed using ternary operator instead. And also the label would get hidden at low progress values which is now 

Fixes #696

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## How Has This Been Tested?

Tested by trying to set the progress value to zero in the storybook.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

### CODE REVIEW

File: src/lib/theme/default.ts [hunk 1]
```diff
@@ -491,12 +491,12 @@ const theme: FlowbiteTheme = {
   },
   listGroup: {
     root: {
-      base: 'list-none rounded-lg border border-gray-200 bg-white text-sm font-medium text-gray-900 dark:border-gray-600 dark:bg-gray-700 dark:text-white text-left',
+      base: 'list-none rounded-lg border border-gray-200 bg-white text-sm font-medium text-gray-900 dark:border-gray-600 dark:bg-gray-700 dark:text-white',
     },
     item: {
-      base: '[&>*]:first:rounded-t-lg [&>*]:last:rounded-b-lg [&>*]:last:border-b-0',
+      base: 'flex w-full cursor-pointer border-b border-gray-200 py-2 px-4 first:rounded-t-lg last:rounded-b-lg last:border-b-0 dark:border-gray-600',
```
Comment (rluders) [inline src/lib/theme/default.ts:497]: This one seems to be unrelated, and it is reverting #668. Is it intentional?

File: src/lib/components/Progress/Progress.tsx [hunk 2]
```diff
@@ -53,27 +53,32 @@ export const Progress: FC<ProgressProps> = ({
...
             {textLabel && labelText && textLabelPosition === 'inside' && (
-              <span data-testid="flowbite-progress-inner-text-label">{textLabel}</span>
+              <span className="whitespace-nowrap" data-testid="flowbite-progress-inner-text-label">
+                {textLabel}
+              </span>
             )}
-            {progress && labelProgress && progressLabelPosition === 'inside' && (
-              <span data-testid="flowbite-progress-inner-progress-label">{progress}%</span>
+            {labelProgress && progressLabelPosition === 'inside' && (
+              <span className="whitespace-nowrap" data-testid="flowbite-progress-inner-progress-label">
```
Comment (rluders) [inline src/lib/components/Progress/Progress.tsx:79]: This class needs to be moved to the theme.

File: src/lib/components/Progress/Progress.tsx [hunk 3]
```diff
@@ -53,27 +53,32 @@ export const Progress: FC<ProgressProps> = ({
...
+        ) : null}
+
         <div className={classNames(theme.base, theme.size[size], className)}>
           <div
             style={{ width: `${progress}%` }}
             className={classNames(theme.bar, theme.color[color], theme.size[size])}
           >
             {textLabel && labelText && textLabelPosition === 'inside' && (
-              <span data-testid="flowbite-progress-inner-text-label">{textLabel}</span>
+              <span className="whitespace-nowrap" data-testid="flowbite-progress-inner-text-label">
```
Comment (rluders) [inline src/lib/components/Progress/Progress.tsx:74]: This class needs to be moved to the theme.

File: src/lib/theme/default.ts [hunk 4]
```diff
@@ -491,12 +491,12 @@ const theme: FlowbiteTheme = {
   },
   listGroup: {
     root: {
-      base: 'list-none rounded-lg border border-gray-200 bg-white text-sm font-medium text-gray-900 dark:border-gray-600 dark:bg-gray-700 dark:text-white text-left',
+      base: 'list-none rounded-lg border border-gray-200 bg-white text-sm font-medium text-gray-900 dark:border-gray-600 dark:bg-gray-700 dark:text-white',
```
Comment (rluders) [inline src/lib/theme/default.ts:494]: This one seems to be unrelated, and it is reverting https://github.com/themesberg/flowbite-react/pull/668. Is it intentional?

File: src/lib/theme/default.ts [hunk 5]
```diff
@@ -491,12 +491,12 @@ const theme: FlowbiteTheme = {
...
     },
     item: {
-      base: '[&>*]:first:rounded-t-lg [&>*]:last:rounded-b-lg [&>*]:last:border-b-0',
+      base: 'flex w-full cursor-pointer border-b border-gray-200 py-2 px-4 first:rounded-t-lg last:rounded-b-lg last:border-b-0 dark:border-gray-600',
       link: {
-        base: 'flex w-full border-b border-gray-200 py-2 px-4 dark:border-gray-600',
+        base: '',
```
Comment (rluders) [inline src/lib/theme/default.ts:499]: This one seems to be unrelated, and it is reverting https://github.com/themesberg/flowbite-react/pull/668. Is it intentional?

**Review by rluders — CHANGES_REQUESTED** [review]

File: src/lib/theme/default.ts (hunk 1 above)
Comment (SrivatsaRUpadhya) [reply src/lib/theme/default.ts:497]: Oh, nope I didn't change anything there!

File: src/lib/components/Progress/Progress.tsx (hunk 3 above)
Comment (SrivatsaRUpadhya) [reply src/lib/components/Progress/Progress.tsx]: It wasn't actually needed. Removed it.
