### PR TITLE
fix(toggleswitch): disable + checked state and deprecated html event replacement

### LINKED ISSUE #986: ToggleSwitch checked={true} disabled={true} not visible
- [X] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [X] I have tested the latest version

## Steps to reproduce

1. Create a toggle switch and set checked={true} and disabled={true}

## Current behavior

- cheked and disabled
image

- not checked and disabled:
image

## Expected behavior

It should be visible showing its status as checked.

### PR DESCRIPTION
**Pull request by rluders**
- [X] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

As described in issue #986 the component `ToggleSwitch` wasn't acting as expected when `checked={true} disabled={true}`. This PR fixes the issue. This also replaces the deprecated `onKeyPress` API with `onKeyDown`.

Fixes #986 

⚠️ This PR replaces the `onKeyPress` with `onKeyDown`. It should not break anything, since the API is only internally used.

### CODE REVIEW

**Review by SutuSebastian — COMMENTED** [review]
Should we take into account throttling? Or this does not cause any issues in this case, if u simply press and hold a button.

File: src/components/ToggleSwitch/ToggleSwitch.tsx [hunk 1]
```diff
@@ -44,16 +44,18 @@ export const ToggleSwitch: FC<ToggleSwitchProps> = ({
 }) => {
   const id = useId();
   const theme = mergeDeep(useTheme().theme.toggleSwitch, customTheme);
+  const buttonRef = useRef<HTMLButtonElement>(null);
```
Comment (SutuSebastian) [inline src/components/ToggleSwitch/ToggleSwitch.tsx:47]: isn't this redundant not being used anywhere? 🤔

Comment (rluders) [reply src/components/ToggleSwitch/ToggleSwitch.tsx:47]: Yes. Dead code. Thanks for noticing.

**Review by SutuSebastian — APPROVED** [review]
