### PR TITLE
fix: pagination button not being highlighted correctly

### LINKED ISSUE #719: Bug with Pagination as current page selection is not visible.
**Describe the bug**

When using the Pagination component in Flowbite React with Tailwind CSS in a NextJS project, the background or interface change for the current page indicator does not appear to be working.

**Screenshots**
image

**System information:**

- Device: Core i7
- Resolution: 1080p
- OS: Windows 11
- Browser: Chrome
- Version: latest

**Project information:**

- Tailwind: 3.3.1
- Flowbite: ^1.6.5
- Flowbite React: ^0.4.3
- Type: CRA

### PR DESCRIPTION
**Pull request by IuriPires**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

A unnecessary Tailwind class was being used causing the PaginationButton to not highlight itself correctly when active.

Fixes #719

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change contains documentation update

## Breaking changes

Please document the breaking changes if suitable.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

For testing this fix, I ran Storybook locally to make sure the fix would be enough. Now the current page selected button is being highlighted correctly both on light and dark mode.

**Test Configuration**:

- Firmware version:
- Hardware: Macbook Pro M1
- Toolchain:
- SDK:

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings

### CODE REVIEW

**Comment by IuriPires** [comment]
Hey @rluders could you check this one, please? :D

File: src/lib/theme/default.ts [hunk 1]
```diff
@@ -630,7 +630,7 @@ const theme: FlowbiteTheme = {
         icon: 'h-5 w-5',
       },
       selector: {
-        base: 'w-12 border border-gray-300 bg-white py-2 leading-tight text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white',
+        base: 'w-12 border border-gray-300 py-2 leading-tight text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:border-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:hover:bg-gray-700 dark:hover:text-white',
```
Comment (rluders) [inline src/lib/theme/default.ts:633]: I think that removing the `bg-white` here isn't the best approach, 'cause, well... you will still have the problem with `dark:bg-gray-800`... Right? So, I would instead look at the `active` and make the `bg-blue-50` and `dark:bg-gray-700` important so that they can overwrite the standard bg from the base.

**Review by rluders — CHANGES_REQUESTED** [review]

File: src/lib/theme/default.ts (hunk 1 above)
Comment (IuriPires) [reply src/lib/theme/default.ts:633]: @rluders totally makes sense. I will perform this little change.

Comment (IuriPires) [reply src/lib/theme/default.ts]: @rluders Done! Check it please as soon as you can :D

**Review by rluders — APPROVED** [review]
