### PR TITLE
fix(Datepicker): expose focus() and clear() methods via ref.

### LINKED ISSUE #1299: Datepicker should `forwardRef`
- [x] I have searched the [Issues](https://github.com/themesberg/flowbite-react/issues) to see if this bug has already been reported
- [x] I have tested the latest version

## Summary

It should be possible to forward `ref` to the Datepicker, in order to focus its input, or clear the value.

Currently the Datepicker is uncontrolled (only accepting `defaultValue`, not `value` prop) https://github.com/themesberg/flowbite-react/issues/1039.
Alternative to controlled component is programmatic API exposing methods to the ref object via [ `useImperativeHandle`](https://react.dev/reference/react/useImperativeHandle).

### Scenario - Clear Datepicker
I have a [controlled Datepicker ](https://form-atoms.github.io/flowbite/?path=/story/datepickerfield--optional) which a problematic scenario:
1. select a value in the datepicker
2. click reset
3. the controlled value is reset, the placeholder is displayed (everything ok on the outside)
4. open the datepicker again
5. the datepicker displays the value from the step 1, expected would be to see the `defaultValue` - a `clear()` method needs to be called.

### Scenario - Focus the datepicker
My controlled form fields, have `focus()` method, where I can focus the field when its appropriate - e.g. error is detected while submitting the form.

Currently I cannot propagate my `ref` to the `Datepicker`. So the Datepicker should accept the ref, and delegate the `focus` call into the 
internal `inputRef` as `inputRef.current.focus()` called in `useImperativeHandle`.

## Additional 
Possibly other methods, like `blur()` could be added, I don't have real use case for this right now so it's optional.

### PR DESCRIPTION
**Pull request by MiroslavPetrik**
Closes #1299 (possibly #1039)

- [x] I have followed the [Your First Code Contribution section of the Contributing guide](https://github.com/themesberg/flowbite-react/blob/main/CONTRIBUTING.md#your-first-code-contribution)

# Summarize the changes made and the motivation behind them.

Enhanced the Datepicker component to expose `clear()` and `focus()` ref methods.
This is required when datepicker value is in controlled mode.

# Reference related issues using `#` followed by the issue number.
Closes #1299 and (possibly #1039)

If there are breaking API changes - like adding or removing props, or changing the structure of the theme - describe them, and provide steps to update existing code.

No breaking changes.

## Summary by CodeRabbit

- **New Features**
	- Enhanced the Datepicker component to support direct manipulation through `focus` and `clear` methods.
- **Refactor**
	- Improved the Datepicker component's architecture for better usability and control.
- **Tests**
	- Added new tests to ensure the functionality of focusing and clearing values in the Datepicker component.

### CODE REVIEW

File: src/components/Datepicker/Datepicker.tsx [hunk 1]
```diff
@@ -325,4 +355,6 @@ export const Datepicker: FC<DatepickerProps> = ({
   );
 };
 
+export const Datepicker = forwardRef(DatepickerRender);
```
Comment (MiroslavPetrik) [inline src/components/Datepicker/Datepicker.tsx:358]: I'm using the forwrdRef call separatelly, as having it together with the DatepickerRender adds unnecessary indentation.

Comment (SutuSebastian) [reply src/components/Datepicker/Datepicker.tsx:358]: agreed

**Comment by anshul-kai** [comment]
Calling `clear()` doesn't clear the rendered value. For folks looking for an interim hack, try the following approach using a `key`.

```
  const ref = useRef<DatepickerRef>(null);
  const [key, setKey] = useState(Date.now());

  useEffect(() => {
    if (value === null) {
      ref.current?.clear();
      setKey(Date.now());
    }
  }, [value]);

  return (
    <Flowbite theme={{ theme: customTheme }}>
      <Datepicker
        ref={ref}
        key={key}
        value={value}
        onChange={onChange}
      />
    </Flowbite>
  );
```
